export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_CREATION_ERROR = 'USER_CREATION_ERROR',
  USER_UPDATE_ERROR = 'USER_UPDATE_ERROR',
  GENERIC = 'GENERIC',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  EMAIL_SENDING_ERROR = 'EMAIL_SENDING_ERROR',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
}
